import { ThemeProvider } from "next-themes";
import "./globals.css";
import Home from "./page";

export const metadata = {
  title: "Harshit S. Parkar's Portfolio",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout() {
  return (
    <html>
      <body>
        <ThemeProvider attribute="class">
          <Home />
        </ThemeProvider>
      </body>
    </html>
  );
}
